package main

import "pisa_server/internal/pkg/perm"

// permRoutes 路由 → 权限 key 映射（key 为 "METHOD /api/shop/..."）
func permRoutes() perm.Routes {
	return perm.Routes{
		// 商品
		"GET /api/shop/goods/list":      perm.GoodsView,
		"GET /api/shop/goods/all":       perm.GoodsView,
		"GET /api/shop/goods/next-code": perm.GoodsAdd,
		"GET /api/shop/goods/brands":    perm.GoodsView,
		"GET /api/shop/goods/origins":   perm.GoodsView,
		"GET /api/shop/goods/:id":       perm.GoodsView,
		"POST /api/shop/goods":          perm.GoodsAdd,
		"POST /api/shop/goods/batch":    perm.GoodsEdit,
		"PUT /api/shop/goods/:id":       perm.GoodsEdit,
		"DELETE /api/shop/goods/:id":    perm.GoodsDel,
		// 商品分类（并入商品）
		"GET /api/shop/category/all":    perm.GoodsView,
		"POST /api/shop/category":       perm.GoodsAdd,
		"PUT /api/shop/category/:id":    perm.GoodsEdit,
		"DELETE /api/shop/category/:id": perm.GoodsDel,
		// 单位管理
		"GET /api/shop/unit/all":    perm.UnitView,
		"POST /api/shop/unit":       perm.UnitAdd,
		"PUT /api/shop/unit/:id":    perm.UnitEdit,
		"DELETE /api/shop/unit/:id": perm.UnitDel,
		// 商品属性
		"GET /api/shop/attribute/all":        perm.AttrView,
		"GET /api/shop/attribute/list":       perm.AttrView,
		"POST /api/shop/attribute":           perm.AttrAdd,
		"PUT /api/shop/attribute/:id":        perm.AttrEdit,
		"DELETE /api/shop/attribute/:id":     perm.AttrDel,
		"POST /api/shop/attribute/:id/value": perm.AttrEdit,
		"GET /api/shop/property/all":         perm.AttrView,
		"POST /api/shop/property":            perm.AttrAdd,
		"PUT /api/shop/property/:id":         perm.AttrEdit,
		"DELETE /api/shop/property/:id":      perm.AttrDel,
		// 价格管理
		"GET /api/shop/price/list":  perm.GoodsPriceView,
		"PUT /api/shop/price/batch": perm.GoodsPriceEdit,
		"PUT /api/shop/price/rows":  perm.GoodsPriceEdit,
		// 套餐
		"GET /api/shop/combo/list":         perm.ComboView,
		"GET /api/shop/combo/price-levels": perm.ComboView,
		"GET /api/shop/combo/:id":          perm.ComboView,
		"POST /api/shop/combo":             perm.ComboAdd,
		"DELETE /api/shop/combo/:id":       perm.ComboDel,
		// 客户
		"GET /api/shop/customer/list":          perm.CustomerView,
		"GET /api/shop/customer/all":           perm.CustomerView,
		"GET /api/shop/customer/:id":           perm.CustomerView,
		"POST /api/shop/customer":              perm.CustomerAdd,
		"PUT /api/shop/customer/:id":           perm.CustomerEdit,
		"DELETE /api/shop/customer/:id":        perm.CustomerDel,
		"GET /api/shop/customer/statement/:id": perm.CustomerView,
		"GET /api/shop/customer/stats/:id":     perm.CustomerView,
		// 客户分类
		"GET /api/shop/customer-category/list":   perm.CustomerView,
		"POST /api/shop/customer-category":       perm.CustomerAdd,
		"PUT /api/shop/customer-category/:id":    perm.CustomerEdit,
		"DELETE /api/shop/customer-category/:id": perm.CustomerDel,
		// 价格等级
		"GET /api/shop/price-level/list":   perm.CustomerLevelView,
		"POST /api/shop/price-level":       perm.CustomerLevelAdd,
		"PUT /api/shop/price-level/:id":    perm.CustomerLevelEdit,
		"DELETE /api/shop/price-level/:id": perm.CustomerLevelDel,
		// 报价管理
		"GET /api/shop/customer-price/list":            perm.CustomerQuoteView,
		"GET /api/shop/customer-price/by-customer/:id": perm.CustomerQuoteView,
		"GET /api/shop/customer-price/by-goods/:id":    perm.CustomerQuoteView,
		"POST /api/shop/customer-price/save":           perm.CustomerQuoteEdit,
		"GET /api/shop/customer-price/history/:id":     perm.CustomerQuoteView,
		// 商户信息
		"GET /api/shop/tenant-info": perm.TenantView,
		"PUT /api/shop/tenant-info": perm.TenantEdit,
		// 仓库管理
		"GET /api/shop/warehouse/list":   perm.WarehouseView,
		"GET /api/shop/warehouse/all":    perm.WarehouseView,
		"GET /api/shop/warehouse/:id":    perm.WarehouseView,
		"POST /api/shop/warehouse":       perm.WarehouseAdd,
		"PUT /api/shop/warehouse/:id":    perm.WarehouseEdit,
		"DELETE /api/shop/warehouse/:id": perm.WarehouseDel,
		// 账户
		"GET /api/shop/account/list":   perm.AccountView,
		"GET /api/shop/account/all":    perm.AccountView,
		"GET /api/shop/account/:id":    perm.AccountView,
		"POST /api/shop/account":       perm.AccountAdd,
		"PUT /api/shop/account/:id":    perm.AccountEdit,
		"DELETE /api/shop/account/:id": perm.AccountDel,
		// 员工管理
		"GET /api/shop/staff/users":        perm.StaffView,
		"POST /api/shop/staff/users":       perm.StaffAdd,
		"PUT /api/shop/staff/users/:id":    perm.StaffEdit,
		"DELETE /api/shop/staff/users/:id": perm.StaffDel,
		"GET /api/shop/salesmen":           perm.StaffView,
		"POST /api/shop/salesmen":          perm.StaffAdd,
		"PUT /api/shop/salesmen/:id":       perm.StaffEdit,
		"DELETE /api/shop/salesmen/:id":    perm.StaffDel,
		// 门店管理
		"GET /api/shop/shops":        perm.ShopView,
		"POST /api/shop/shops":       perm.ShopAdd,
		"PUT /api/shop/shops/:id":    perm.ShopEdit,
		"DELETE /api/shop/shops/:id": perm.ShopDel,
		// 角色权限
		"GET /api/shop/role/list":   perm.RoleView,
		"GET /api/shop/role/:id":    perm.RoleView,
		"POST /api/shop/role":       perm.RoleAdd,
		"PUT /api/shop/role/:id":    perm.RoleEdit,
		"DELETE /api/shop/role/:id": perm.RoleDel,
		// 系统设置
		"GET /api/shop/system-setting": perm.SystemView,
		"PUT /api/shop/system-setting": perm.SystemEdit,
		// 打印设置
		"GET /api/shop/print-setting": perm.PrintView,
		"PUT /api/shop/print-setting": perm.PrintEdit,
		// 供应商
		"GET /api/shop/supplier/list":            perm.SupplierView,
		"GET /api/shop/supplier/all":             perm.SupplierView,
		"GET /api/shop/supplier/:id":             perm.SupplierView,
		"POST /api/shop/supplier":                perm.SupplierAdd,
		"POST /api/shop/supplier/batch":          perm.SupplierEdit,
		"PUT /api/shop/supplier/:id":             perm.SupplierEdit,
		"DELETE /api/shop/supplier/:id":          perm.SupplierDel,
		"GET /api/shop/supplier-category/all":    perm.SupplierView,
		"POST /api/shop/supplier-category":       perm.SupplierAdd,
		"PUT /api/shop/supplier-category/:id":    perm.SupplierEdit,
		"DELETE /api/shop/supplier-category/:id": perm.SupplierDel,
		// 进货
		"GET /api/shop/purchase/list":              perm.PurchaseView,
		"GET /api/shop/purchase/:id":               perm.PurchaseView,
		"POST /api/shop/purchase":                  perm.PurchaseAdd,
		"PUT /api/shop/purchase/:id":               perm.PurchaseEdit,
		"DELETE /api/shop/purchase/:id":            perm.PurchaseVoid,
		"POST /api/shop/purchase/:id/audit":        perm.PurchaseEdit,
		"POST /api/shop/purchase/:id/unaudit":      perm.PurchaseEdit,
		"GET /api/shop/purchase-return/list":       perm.PurchaseReturnView,
		"GET /api/shop/purchase-return/:id":        perm.PurchaseReturnView,
		"POST /api/shop/purchase-return":           perm.PurchaseReturnAdd,
		"PUT /api/shop/purchase-return/:id":        perm.PurchaseReturnAdd,
		"DELETE /api/shop/purchase-return/:id":     perm.PurchaseReturnVoid,
		"POST /api/shop/purchase-return/:id/audit": perm.PurchaseReturnAdd,
		"GET /api/shop/purchase-order/list":        perm.PurchaseOrderView,
		"GET /api/shop/purchase-order/:id":         perm.PurchaseOrderView,
		"POST /api/shop/purchase-order":            perm.PurchaseOrderAdd,
		"DELETE /api/shop/purchase-order/:id":      perm.PurchaseOrderVoid,
		"POST /api/shop/purchase-order/:id/audit":  perm.PurchaseOrderAdd,
		// 销售
		"GET /api/shop/sale/list":          perm.SaleView,
		"GET /api/shop/sale/:id":           perm.SaleView,
		"POST /api/shop/sale":              perm.SaleAdd,
		"PUT /api/shop/sale/:id":           perm.SaleAdd,
		"DELETE /api/shop/sale/:id":        perm.SaleVoid,
		"GET /api/shop/sale-order/list":    perm.SaleOrderView,
		"GET /api/shop/sale-order/:id":     perm.SaleOrderView,
		"POST /api/shop/sale-order":        perm.SaleOrderAdd,
		"DELETE /api/shop/sale-order/:id":  perm.SaleOrderVoid,
		"GET /api/shop/sale-return/list":   perm.SaleReturnView,
		"GET /api/shop/sale-return/:id":    perm.SaleReturnView,
		"POST /api/shop/sale-return":       perm.SaleReturnAdd,
		"DELETE /api/shop/sale-return/:id": perm.SaleReturnVoid,
		"GET /api/shop/quote/list":         perm.SaleQuoteView,
		"GET /api/shop/quote/:id":          perm.SaleQuoteView,
		"POST /api/shop/quote":             perm.SaleQuoteAdd,
		"DELETE /api/shop/quote/:id":       perm.SaleQuoteVoid,
		// 业绩提成（归入员工业绩）
		"GET /api/shop/commission-rule/list":   perm.AnalysisStaffView,
		"POST /api/shop/commission-rule":       perm.AnalysisStaffView,
		"PUT /api/shop/commission-rule/:id":    perm.AnalysisStaffView,
		"DELETE /api/shop/commission-rule/:id": perm.AnalysisStaffView,
		"GET /api/shop/commission/report":      perm.AnalysisStaffView,
		// 盘点
		"GET /api/shop/stock-count/list":      perm.StockCountView,
		"GET /api/shop/stock-count/:id":       perm.StockCountView,
		"POST /api/shop/stock-count":          perm.StockCountAdd,
		"POST /api/shop/stock-count/:id/void": perm.StockCountVoid,
		// 组装
		"GET /api/shop/assembly/list":      perm.AssemblyView,
		"GET /api/shop/assembly/:id":       perm.AssemblyView,
		"POST /api/shop/assembly":          perm.AssemblyAdd,
		"PUT /api/shop/assembly/:id":       perm.AssemblyEdit,
		"POST /api/shop/assembly/:id/void": perm.AssemblyVoid,
		// 拆分
		"GET /api/shop/split/list":      perm.SplitView,
		"GET /api/shop/split/:id":       perm.SplitView,
		"POST /api/shop/split":          perm.SplitAdd,
		"PUT /api/shop/split/:id":       perm.SplitEdit,
		"POST /api/shop/split/:id/void": perm.SplitVoid,
		// 配方（并入组装）
		"GET /api/shop/recipe/list":   perm.AssemblyView,
		"GET /api/shop/recipe/:id":    perm.AssemblyView,
		"POST /api/shop/recipe":       perm.AssemblyAdd,
		"PUT /api/shop/recipe/:id":    perm.AssemblyEdit,
		"DELETE /api/shop/recipe/:id": perm.AssemblyVoid,
		// 库存查询/预警/批次/保质期
		"GET /api/shop/stock-query/list":     perm.StockQueryView,
		"GET /api/shop/stock-query/alert":    perm.StockAlertView,
		"GET /api/shop/stock-query/flow/:id": perm.StockQueryView,
		"GET /api/shop/stock-query/cost/:id": perm.StockQueryCost,
		"GET /api/shop/batch/list":           perm.StockBatchView,
		"GET /api/shop/batch/expiry":         perm.StockExpiryView,
		// 转账
		"GET /api/shop/transfer/list": perm.TransferView,
		"POST /api/shop/transfer":     perm.TransferAdd,
		// 收款
		"GET /api/shop/receipt/list":      perm.ReceiptView,
		"GET /api/shop/receipt/:id":       perm.ReceiptView,
		"POST /api/shop/receipt":          perm.ReceiptAdd,
		"PUT /api/shop/receipt/:id":       perm.ReceiptEdit,
		"POST /api/shop/receipt/:id/void": perm.ReceiptVoid,
		// 付款
		"GET /api/shop/payment/list":      perm.PaymentView,
		"GET /api/shop/payment/:id":       perm.PaymentView,
		"POST /api/shop/payment":          perm.PaymentAdd,
		"PUT /api/shop/payment/:id":       perm.PaymentEdit,
		"POST /api/shop/payment/:id/void": perm.PaymentVoid,
		// 收支类型
		"GET /api/shop/income-type/list":   perm.IncomeTypeView,
		"POST /api/shop/income-type":       perm.IncomeTypeAdd,
		"PUT /api/shop/income-type/:id":    perm.IncomeTypeEdit,
		"DELETE /api/shop/income-type/:id": perm.IncomeTypeDel,
		// 其它收入
		"GET /api/shop/income/list":      perm.IncomeView,
		"GET /api/shop/income/:id":       perm.IncomeView,
		"POST /api/shop/income":          perm.IncomeAdd,
		"PUT /api/shop/income/:id":       perm.IncomeEdit,
		"POST /api/shop/income/:id/void": perm.IncomeVoid,
		// 其它支出
		"GET /api/shop/expense/list":      perm.ExpenseView,
		"GET /api/shop/expense/:id":       perm.ExpenseView,
		"POST /api/shop/expense":          perm.ExpenseAdd,
		"PUT /api/shop/expense/:id":       perm.ExpenseEdit,
		"POST /api/shop/expense/:id/void": perm.ExpenseVoid,
		// 对账 / 资金流水
		"GET /api/shop/reconcile/customer": perm.CustomerReconView,
		"GET /api/shop/reconcile/supplier": perm.SupplierReconView,
		"GET /api/shop/fund-flow/list":     perm.CashflowView,
		// 分析
		"GET /api/shop/sales-stat/doc":             perm.AnalysisSalesView,
		"GET /api/shop/sales-stat/goods":           perm.AnalysisSalesView,
		"GET /api/shop/sales-stat/customer":        perm.AnalysisSalesView,
		"GET /api/shop/analysis/hot-sales":         perm.AnalysisHotView,
		"GET /api/shop/analysis/staff-perf":        perm.AnalysisStaffView,
		"GET /api/shop/analysis/purchase-goods":    perm.AnalysisPurchaseView,
		"GET /api/shop/analysis/purchase-supplier": perm.AnalysisPurchaseView,
		"GET /api/shop/analysis/stock-stat":        perm.AnalysisStockView,
		"GET /api/shop/analysis/profit":            perm.AnalysisProfitView,
		"GET /api/shop/analysis/surplus-detail":    perm.AnalysisProfitView,
		"GET /api/shop/analysis/loss-detail":       perm.AnalysisProfitView,
	}
}
