-- ============================================
-- PISA 进销存 - 物理分表建表脚本
-- 分片算法: tenant_id % 16
-- 表命名: {表名}_t{分片号, 两位补零}
-- ============================================
-- 用法: mysql -u root -p pisa_shop < sql/sharded_tables.sql
-- 或 Go 代码中调用 db.CreateShardedTables() 自动创建
-- ============================================

-- ==================== sales (销货单) ====================
CREATE TABLE IF NOT EXISTS sales_t00 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t01 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t02 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t03 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t04 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t05 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t06 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t07 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t08 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t09 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t10 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t11 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t12 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t13 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t14 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales_t15 (id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, shop_id BIGINT, warehouse_id BIGINT, order_no VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, bill_date DATE NOT NULL, total_amount DECIMAL(10,2) DEFAULT 0, received_amount DECIMAL(10,2) DEFAULT 0, unreceived_amount DECIMAL(10,2) DEFAULT 0, status TINYINT DEFAULT 1, remark VARCHAR(500), created_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uk_order_no (tenant_id, order_no), INDEX idx_tenant_date (tenant_id, bill_date), INDEX idx_tenant_customer (tenant_id, customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
